In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of the words',
    'your videos are good'
    ]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of the words',
 'your videos are good']

In [4]:
## Define the vocabulary size 
voc_size=10000

In [5]:
### One hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[1240, 5309, 5739, 796],
 [1240, 5309, 5739, 764],
 [1240, 2615, 5739, 9986],
 [5124, 5374, 4368, 6813, 1921],
 [5124, 5374, 4368, 6813, 6203],
 [7196, 1240, 1854, 5739, 1240, 2795],
 [9649, 9631, 8877, 6813]]

In [6]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(
    one_hot_repr,
    padding='pre',
    maxlen=sent_length
    )

In [9]:
print(embedded_docs)

[[   0    0    0    0 1240 5309 5739  796]
 [   0    0    0    0 1240 5309 5739  764]
 [   0    0    0    0 1240 2615 5739 9986]
 [   0    0    0 5124 5374 4368 6813 1921]
 [   0    0    0 5124 5374 4368 6813 6203]
 [   0    0 7196 1240 1854 5739 1240 2795]
 [   0    0    0    0 9649 9631 8877 6813]]


In [10]:
## feature representation
dim=10

In [11]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.build(input_shape=(None, sent_length))
model.summary()


d:\DL_NLP_Bootcamp\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


array([[[-0.04875277, -0.0198222 ,  0.04555969, -0.00371636,
         -0.03154258, -0.01009408, -0.03555883,  0.00976294,
          0.04221984,  0.04969299],
        [-0.04875277, -0.0198222 ,  0.04555969, -0.00371636,
         -0.03154258, -0.01009408, -0.03555883,  0.00976294,
          0.04221984,  0.04969299],
        [-0.04875277, -0.0198222 ,  0.04555969, -0.00371636,
         -0.03154258, -0.01009408, -0.03555883,  0.00976294,
          0.04221984,  0.04969299],
        [-0.04875277, -0.0198222 ,  0.04555969, -0.00371636,
         -0.03154258, -0.01009408, -0.03555883,  0.00976294,
          0.04221984,  0.04969299],
        [-0.00908114, -0.04733706, -0.03386684, -0.01873659,
         -0.02117455,  0.02309194, -0.03952886,  0.02205983,
         -0.03641859,  0.01564621],
        [ 0.01268   ,  0.00548614,  0.00726516,  0.02853271,
          0.01425905, -0.04314956,  0.03770093, -0.0014726 ,
          0.02777297, -0.01829523],
        [ 0.01842579, -0.03965223,  0.02527925,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 1240, 5309, 5739,  796])

In [15]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


array([[[-0.04875277, -0.0198222 ,  0.04555969, -0.00371636,
         -0.03154258, -0.01009408, -0.03555883,  0.00976294,
          0.04221984,  0.04969299],
        [-0.04875277, -0.0198222 ,  0.04555969, -0.00371636,
         -0.03154258, -0.01009408, -0.03555883,  0.00976294,
          0.04221984,  0.04969299],
        [-0.04875277, -0.0198222 ,  0.04555969, -0.00371636,
         -0.03154258, -0.01009408, -0.03555883,  0.00976294,
          0.04221984,  0.04969299],
        [-0.04875277, -0.0198222 ,  0.04555969, -0.00371636,
         -0.03154258, -0.01009408, -0.03555883,  0.00976294,
          0.04221984,  0.04969299],
        [-0.00908114, -0.04733706, -0.03386684, -0.01873659,
         -0.02117455,  0.02309194, -0.03952886,  0.02205983,
         -0.03641859,  0.01564621],
        [ 0.01268   ,  0.00548614,  0.00726516,  0.02853271,
          0.01425905, -0.04314956,  0.03770093, -0.0014726 ,
          0.02777297, -0.01829523],
        [ 0.01842579, -0.03965223,  0.02527925,  0.0